// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/refresh': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/refresh.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/user.get').default>>>>
    }
    '/api/tweets/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tweets/[id].get').default>>>>
    }
    '/api/tweets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tweets/index.get').default>>>>
    }
    '/api/user/tweets': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/tweets/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}