
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AuthForm': typeof import("../components/Auth/Form.vue")['default']
    'AuthPage': typeof import("../components/Auth/Page.vue")['default']
    'Loading': typeof import("../components/Loading.vue")['default']
    'LogoTwitter': typeof import("../components/Logo/Twitter.vue")['default']
    'MainSection': typeof import("../components/MainSection.vue")['default']
    'SidebarLeftTab': typeof import("../components/Sidebar/Left/Tab.vue")['default']
    'SidebarLeft': typeof import("../components/Sidebar/Left/index.vue")['default']
    'SidebarRightPreviewCard': typeof import("../components/Sidebar/Right/PreviewCard/index.vue")['default']
    'SidebarRightPreviewCardItem': typeof import("../components/Sidebar/Right/PreviewCard/item.vue")['default']
    'SidebarRight': typeof import("../components/Sidebar/Right/index.vue")['default']
    'TweetDetails': typeof import("../components/Tweet/Details.vue")['default']
    'TweetFormInput': typeof import("../components/Tweet/Form/Input.vue")['default']
    'TweetForm': typeof import("../components/Tweet/Form/index.vue")['default']
    'TweetItemActionsIcon': typeof import("../components/Tweet/Item/Actions/Icon.vue")['default']
    'TweetItemActions': typeof import("../components/Tweet/Item/Actions/index.vue")['default']
    'TweetItemHeader': typeof import("../components/Tweet/Item/Header.vue")['default']
    'TweetItem': typeof import("../components/Tweet/Item/index.vue")['default']
    'TweetListFeed': typeof import("../components/Tweet/ListFeed.vue")['default']
    'UIButton': typeof import("../components/UI/Button.vue")['default']
    'UIIcon': typeof import("../components/UI/Icon.vue")['default']
    'UIInput': typeof import("../components/UI/Input.vue")['default']
    'UIModal': typeof import("../components/UI/Modal.vue")['default']
    'UISpinner': typeof import("../components/UI/Spinner.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAuthForm': typeof import("../components/Auth/Form.vue")['default']
    'LazyAuthPage': typeof import("../components/Auth/Page.vue")['default']
    'LazyLoading': typeof import("../components/Loading.vue")['default']
    'LazyLogoTwitter': typeof import("../components/Logo/Twitter.vue")['default']
    'LazyMainSection': typeof import("../components/MainSection.vue")['default']
    'LazySidebarLeftTab': typeof import("../components/Sidebar/Left/Tab.vue")['default']
    'LazySidebarLeft': typeof import("../components/Sidebar/Left/index.vue")['default']
    'LazySidebarRightPreviewCard': typeof import("../components/Sidebar/Right/PreviewCard/index.vue")['default']
    'LazySidebarRightPreviewCardItem': typeof import("../components/Sidebar/Right/PreviewCard/item.vue")['default']
    'LazySidebarRight': typeof import("../components/Sidebar/Right/index.vue")['default']
    'LazyTweetDetails': typeof import("../components/Tweet/Details.vue")['default']
    'LazyTweetFormInput': typeof import("../components/Tweet/Form/Input.vue")['default']
    'LazyTweetForm': typeof import("../components/Tweet/Form/index.vue")['default']
    'LazyTweetItemActionsIcon': typeof import("../components/Tweet/Item/Actions/Icon.vue")['default']
    'LazyTweetItemActions': typeof import("../components/Tweet/Item/Actions/index.vue")['default']
    'LazyTweetItemHeader': typeof import("../components/Tweet/Item/Header.vue")['default']
    'LazyTweetItem': typeof import("../components/Tweet/Item/index.vue")['default']
    'LazyTweetListFeed': typeof import("../components/Tweet/ListFeed.vue")['default']
    'LazyUIButton': typeof import("../components/UI/Button.vue")['default']
    'LazyUIIcon': typeof import("../components/UI/Icon.vue")['default']
    'LazyUIInput': typeof import("../components/UI/Input.vue")['default']
    'LazyUIModal': typeof import("../components/UI/Modal.vue")['default']
    'LazyUISpinner': typeof import("../components/UI/Spinner.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AuthForm: typeof import("../components/Auth/Form.vue")['default']
export const AuthPage: typeof import("../components/Auth/Page.vue")['default']
export const Loading: typeof import("../components/Loading.vue")['default']
export const LogoTwitter: typeof import("../components/Logo/Twitter.vue")['default']
export const MainSection: typeof import("../components/MainSection.vue")['default']
export const SidebarLeftTab: typeof import("../components/Sidebar/Left/Tab.vue")['default']
export const SidebarLeft: typeof import("../components/Sidebar/Left/index.vue")['default']
export const SidebarRightPreviewCard: typeof import("../components/Sidebar/Right/PreviewCard/index.vue")['default']
export const SidebarRightPreviewCardItem: typeof import("../components/Sidebar/Right/PreviewCard/item.vue")['default']
export const SidebarRight: typeof import("../components/Sidebar/Right/index.vue")['default']
export const TweetDetails: typeof import("../components/Tweet/Details.vue")['default']
export const TweetFormInput: typeof import("../components/Tweet/Form/Input.vue")['default']
export const TweetForm: typeof import("../components/Tweet/Form/index.vue")['default']
export const TweetItemActionsIcon: typeof import("../components/Tweet/Item/Actions/Icon.vue")['default']
export const TweetItemActions: typeof import("../components/Tweet/Item/Actions/index.vue")['default']
export const TweetItemHeader: typeof import("../components/Tweet/Item/Header.vue")['default']
export const TweetItem: typeof import("../components/Tweet/Item/index.vue")['default']
export const TweetListFeed: typeof import("../components/Tweet/ListFeed.vue")['default']
export const UIButton: typeof import("../components/UI/Button.vue")['default']
export const UIIcon: typeof import("../components/UI/Icon.vue")['default']
export const UIInput: typeof import("../components/UI/Input.vue")['default']
export const UIModal: typeof import("../components/UI/Modal.vue")['default']
export const UISpinner: typeof import("../components/UI/Spinner.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAuthForm: typeof import("../components/Auth/Form.vue")['default']
export const LazyAuthPage: typeof import("../components/Auth/Page.vue")['default']
export const LazyLoading: typeof import("../components/Loading.vue")['default']
export const LazyLogoTwitter: typeof import("../components/Logo/Twitter.vue")['default']
export const LazyMainSection: typeof import("../components/MainSection.vue")['default']
export const LazySidebarLeftTab: typeof import("../components/Sidebar/Left/Tab.vue")['default']
export const LazySidebarLeft: typeof import("../components/Sidebar/Left/index.vue")['default']
export const LazySidebarRightPreviewCard: typeof import("../components/Sidebar/Right/PreviewCard/index.vue")['default']
export const LazySidebarRightPreviewCardItem: typeof import("../components/Sidebar/Right/PreviewCard/item.vue")['default']
export const LazySidebarRight: typeof import("../components/Sidebar/Right/index.vue")['default']
export const LazyTweetDetails: typeof import("../components/Tweet/Details.vue")['default']
export const LazyTweetFormInput: typeof import("../components/Tweet/Form/Input.vue")['default']
export const LazyTweetForm: typeof import("../components/Tweet/Form/index.vue")['default']
export const LazyTweetItemActionsIcon: typeof import("../components/Tweet/Item/Actions/Icon.vue")['default']
export const LazyTweetItemActions: typeof import("../components/Tweet/Item/Actions/index.vue")['default']
export const LazyTweetItemHeader: typeof import("../components/Tweet/Item/Header.vue")['default']
export const LazyTweetItem: typeof import("../components/Tweet/Item/index.vue")['default']
export const LazyTweetListFeed: typeof import("../components/Tweet/ListFeed.vue")['default']
export const LazyUIButton: typeof import("../components/UI/Button.vue")['default']
export const LazyUIIcon: typeof import("../components/UI/Icon.vue")['default']
export const LazyUIInput: typeof import("../components/UI/Input.vue")['default']
export const LazyUIModal: typeof import("../components/UI/Modal.vue")['default']
export const LazyUISpinner: typeof import("../components/UI/Spinner.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
