// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/9/2024, 11:22:51 AM
const configMerger = require("D:/Reources/nuxtjs/social-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Reources/nuxtjs/social-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Reources/nuxtjs/social-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Reources/nuxtjs/social-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Reources/nuxtjs/social-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Reources/nuxtjs/social-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Reources/nuxtjs/social-project/plugins/**/*.{js,ts,mjs}","D:/Reources/nuxtjs/social-project/composables/**/*.{js,ts,mjs}","D:/Reources/nuxtjs/social-project/utils/**/*.{js,ts,mjs}","D:/Reources/nuxtjs/social-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Reources/nuxtjs/social-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Reources/nuxtjs/social-project/app.config.{js,ts,mjs}"] }));

module.exports = config
